import JSZip from 'jszip';
import type { Project, ProjectFile } from '../types/saz';

/**
 * Creates and downloads a complete, production-ready ZIP archive of the project.
 */
export async function downloadProjectZip(project: Project): Promise<void> {
  const zip = new JSZip();

  // 1. Add all project files
  const existingFiles = project.files || [];
  const addedPaths = new Set<string>();

  for (const file of existingFiles) {
    const cleanPath = file.path.replace(/^\/+/, '');
    if (!cleanPath) continue;
    zip.file(cleanPath, file.content);
    addedPaths.add(cleanPath);
  }

  // 2. Ensure package.json exists
  if (!addedPaths.has('package.json')) {
    const defaultPackageJson = {
      name: project.slug || 'saz-project',
      private: true,
      version: project.settings?.version || '1.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'vite build',
        preview: 'vite preview',
      },
      dependencies: {
        react: '^19.0.0',
        'react-dom': '^19.0.0',
        'lucide-react': '^0.475.0',
      },
      devDependencies: {
        vite: '^6.1.0',
        tailwindcss: '^4.0.0',
        typescript: '^5.7.0',
      },
    };
    zip.file('package.json', JSON.stringify(defaultPackageJson, null, 2));
  }

  // 3. Ensure .gitignore exists
  if (!addedPaths.has('.gitignore')) {
    const gitignoreContent = `# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed

# Dependency directories
node_modules/

# Build artifacts
dist/
build/
.cache/

# Environment variables
.env
.env.local
.env.*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`;
    zip.file('.gitignore', gitignoreContent);
  }

  // 4. Ensure README.md exists
  if (!addedPaths.has('README.md')) {
    const readmeContent = `# ${project.name}

> ${project.summary || 'Application generated and managed with SAZ Builder.'}

## 📋 Overview

- **Framework**: ${project.framework || 'React + TypeScript + Tailwind'}
- **Category**: ${project.category || 'Application'}
- **Status**: ${project.status || 'Active'}
- **Created with**: SAZ Builder (Autonomous Architecture Platform)

## 🚀 Quick Start

Run this project locally in seconds:

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Start local development server
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) (or the port indicated in terminal) in your browser.

## 📦 Production Build

\`\`\`bash
# Build for production
npm run build

# Preview production build locally
npm run preview
\`\`\`

## 🌐 Deployment Options

### GitHub Pages
1. Push this project to your GitHub repository.
2. In your repository on GitHub, navigate to **Settings > Pages**.
3. Under **Build and deployment > Source**, select **GitHub Actions** (the provided \`.github/workflows/deploy.yml\` handles everything).

### Vercel / Netlify
1. Connect your GitHub repository to [Vercel](https://vercel.com) or [Netlify](https://netlify.com).
2. Set build command to \`npm run build\` and output directory to \`dist\` (or root for static apps).
3. Click **Deploy**.

### Docker Container
\`\`\`bash
docker build -t ${project.slug} .
docker run -p 8080:80 ${project.slug}
\`\`\`

## 📁 Project Architecture & Files

${existingFiles.map((f) => `- \`${f.path}\` (${f.language})`).join('\n')}

---
Generated by **SAZ Builder** · Architecture Engine
`;
    zip.file('README.md', readmeContent);
  }

  // 5. Ensure saz.config.json exists
  if (!addedPaths.has('saz.config.json')) {
    const sazConfig = {
      id: project.id,
      name: project.name,
      slug: project.slug,
      summary: project.summary,
      framework: project.framework,
      category: project.category,
      modules: project.modules,
      settings: project.settings,
      exportedAt: new Date().toISOString(),
    };
    zip.file('saz.config.json', JSON.stringify(sazConfig, null, 2));
  }

  // 6. Generate ZIP Blob and trigger browser download
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.slug || 'project'}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Downloads single standalone HTML file.
 */
export function downloadSingleFileHtml(project: Project): void {
  const content =
    project.previewHtml ||
    project.files.find((f) => f.path.toLowerCase() === 'index.html')?.content ||
    '<!DOCTYPE html><html><body><h1>Empty Project</h1></body></html>';

  const blob = new Blob([content], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.slug || 'project'}-standalone.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generic file downloader.
 */
export function downloadFile(filename: string, content: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export interface ExtractedProjectResult {
  name: string;
  slug: string;
  summary: string;
  framework: string;
  files: ProjectFile[];
  previewHtml?: string;
  folders: string[];
}

/**
 * Extracts and reconstructs a project from an uploaded ZIP archive.
 */
export async function extractProjectFromZip(file: File): Promise<ExtractedProjectResult> {
  const zip = await JSZip.loadAsync(file);
  const files: ProjectFile[] = [];
  const foldersSet = new Set<string>();

  let sazConfigContent: string | null = null;
  let packageJsonContent: string | null = null;
  let readmeContent: string | null = null;
  let indexHtmlContent: string | null = null;

  // Process all files in zip
  const entries: Array<{ relativePath: string; zipEntry: JSZip.JSZipObject }> = [];
  zip.forEach((relativePath, zipEntry) => {
    entries.push({ relativePath, zipEntry });
  });

  for (const { relativePath, zipEntry } of entries) {
    // Ignore directories and system hidden files
    if (zipEntry.dir) {
      foldersSet.add(relativePath.replace(/\/$/, ''));
      continue;
    }
    if (
      relativePath.startsWith('__MACOSX/') ||
      relativePath.includes('/.DS_Store') ||
      relativePath.endsWith('.DS_Store') ||
      relativePath.includes('node_modules/')
    ) {
      continue;
    }

    // Determine folder path
    const parts = relativePath.split('/');
    if (parts.length > 1) {
      for (let i = 1; i < parts.length; i++) {
        foldersSet.add(parts.slice(0, i).join('/'));
      }
    }

    try {
      const content = await zipEntry.async('string');
      const filename = relativePath.toLowerCase();

      if (filename === 'saz.config.json' || filename.endsWith('/saz.config.json')) {
        sazConfigContent = content;
      }
      if (filename === 'package.json' || filename.endsWith('/package.json')) {
        packageJsonContent = content;
      }
      if (filename === 'readme.md' || filename.endsWith('/readme.md')) {
        readmeContent = content;
      }
      if (filename === 'index.html' || filename.endsWith('/index.html')) {
        indexHtmlContent = content;
      }

      const ext = relativePath.split('.').pop()?.toLowerCase() || '';
      const langMap: Record<string, string> = {
        ts: 'typescript',
        tsx: 'typescript',
        js: 'javascript',
        jsx: 'javascript',
        json: 'json',
        html: 'html',
        css: 'css',
        md: 'markdown',
        yml: 'yaml',
        yaml: 'yaml',
        sql: 'sql',
      };

      files.push({
        path: relativePath,
        language: langMap[ext] || 'text',
        content,
        updatedAt: new Date().toISOString(),
      });
    } catch (err) {
      console.warn(`Could not read file ${relativePath} as string:`, err);
    }
  }

  if (files.length === 0) {
    throw new Error('No valid text or code files found in the provided ZIP archive.');
  }

  // Derive metadata
  let name = file.name.replace(/\.zip$/i, '').replace(/[-_]+/g, ' ');
  // Capitalize title
  name = name
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  let summary = 'Project imported from ZIP archive';
  let framework = 'React + TypeScript + Tailwind';

  if (sazConfigContent) {
    try {
      const parsed = JSON.parse(sazConfigContent);
      if (parsed.name) name = parsed.name;
      if (parsed.summary) summary = parsed.summary;
      if (parsed.framework) framework = parsed.framework;
    } catch {}
  } else if (packageJsonContent) {
    try {
      const pkg = JSON.parse(packageJsonContent);
      if (pkg.name) {
        name = pkg.name
          .replace(/[-_]+/g, ' ')
          .split(' ')
          .map((w: string) => w.charAt(0).toUpperCase() + w.slice(1))
          .join(' ');
      }
      if (pkg.description) summary = pkg.description;
      if (pkg.dependencies?.next) framework = 'Next.js App Router';
      else if (pkg.dependencies?.express) framework = 'Express + Full-Stack Node';
    } catch {}
  } else if (readmeContent) {
    const firstLine = readmeContent.split('\n')[0]?.replace(/^#+\s*/, '').trim();
    if (firstLine && firstLine.length < 50) name = firstLine;
  }

  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

  return {
    name,
    slug,
    summary,
    framework,
    files,
    folders: Array.from(foldersSet),
    previewHtml: indexHtmlContent || undefined,
  };
}
